### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by Klimbim1** [nctiggy/split-flap-mqtt#1]
Sorry wrong fork, please delete ;)

**Comment by nctiggy** [comment]
Sorry, I am just now seeing this, did you get this all squared away?

**Comment by Klimbim1** [comment]
Hi Craig, I wrongly wrote this into your repo but it affected this fork: https://github.com/derqurps/split-flap, sorry for the mishap ;) the website doesn't load from this fork when I hit the submit button... :(

**Comment by Hopsen** [comment]
Hey, I just installed your fork.
I can see the esp in my wifi and as an port in Arduino IDE. But when I open the IP in the browser no website is loading. Do I need a port to open it?
Thanks.

**Comment by nctiggy** [comment]
Hi! I actually don't have this set up with a web page, rather I use node-red to manage the activity for the split flap. This fork just leverages mqtt as the main transport .

**Comment by Hopsen** [comment]
Ah, alright. I have an instance of nod red running.
Is it possible you share an example of node red flows showing how you use mqtt for the split-flap?

**Comment by nctiggy** [comment]
Yes absolutely,
the flows.json should be able to be directly imported into node-red

You will also need a mqtt server running as well. (I use mosquito) 

All the device config should be in the 01_config.ino file

After you import the flow into node-red you will need to make sure in install any nodes I use the following

Node-red-dashboard
Node-red-contrib-moment
Node-red-contrib-simple-gate
Node-red-node-sqlite

Then you should be able to configure the mqtt nodes to point to your mqtt server, then browse to your node-red URL and append /ui to the end to see the dashboard that should allow you to register your device (I haven’t gotten around to much more functionality yet, let setting messages or having multiples of these work in tandem)

Let me know if you still have any issues

**Comment by Klimbim1** [comment]
Hi all, I haven't been able to use this MQTT at the end so if anyone does, let me know. pls!

**Comment by nctiggy** [comment]
If you would like help, I am more than willing. I think being able to live chat may be the quickest way work through any issues though. I am open to suggestions

**Comment by Hopsen** [comment]
Hey @nctiggy I would appreciate it. Maybe we all could use discord? Prusa Discord for example? 
At the moment I have set the Matt settings and I can see the updates from your example flow in mqtt explorer, but the display does nothing.

**Comment by Hopsen** [comment]
Update: is working now. My fault was that I have just 7 digits yet, but in the code I had 10. Changing it to 7 in the code fixed it.

**Comment by nctiggy** [comment]
Are you asking how to set up MQTT or how to get this pointing to mqtt. I am willing to help with either, some sort of live chat would probably be most efficient but I am open to anything
